apiVersion: apps/v1
kind: Deployment
metadata:
  name: nograceful
  namespace: nograceful
  labels:
    app.kubernetes.io/name: nograceful
    app.kubernetes.io/instance: nograceful
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nograceful
      app.kubernetes.io/instance: nograceful
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nograceful
        app.kubernetes.io/instance: nograceful
    spec:
      containers:
        - name: nograceful
          image: nograceful
          imagePullPolicy: IfNotPresent
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
