apiVersion: v1
kind: Service
metadata:
  name: nograceful
  labels:
    app.kubernetes.io/name: nograceful
    app.kubernetes.io/instance: nograceful
    app.kubernetes.io/component: verification
    app.kubernetes.io/managed-by: kustomize
  namespace: nograceful
spec:
  type: NodePort
  ports:
    - name: http-nograceful
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30007
  selector:
    app.kubernetes.io/name: nograceful
    app.kubernetes.io/instance: nograceful